query ExternalLookupQuery($key: String!) {
  externalCustomerLookup(key: $key) {
    status
    customer {
      externalId
      firstName {
        encrypted
        masked
      }
      email {
        encrypted
        masked
      }
      lastName {
        encrypted
        masked
      }
      address {
        encrypted
        masked
      }
      postalCode {
        encrypted
        masked
      }
      mobilePhoneNumber {
        encrypted
        masked
      }
      city {
        encrypted
        masked
      }
      co {
        encrypted
        masked
      }
    }
  }
}
