query ExternalLookupQuery($key: String!) {
  externalCustomerLookup(key: $key) {
    status
    customer {
      externalId
      firstName {
        encrypted
        masked
      }
      email {
        encrypted
        masked
      }
      lastName {
        encrypted
        masked
      }
      address {
        encrypted
        masked
      }
      postalCode {
        encrypted
        masked
      }
      mobilePhoneNumber {
        encrypted
        masked
      }
      city {
        encrypted
        masked
      }
      co {
        encrypted
        masked
      }
    }
  }
}

query LookupQuery($key: String!) {
  personLookup(key: $key) {
    firstName {
      encrypted
      masked
    }
    lastName {
      encrypted
      masked
    }
    address {
      encrypted
      masked
    }
    postalCode {
      encrypted
      masked
    }
    mobilePhoneNumber {
      encrypted
      masked
    }
    city {
      encrypted
      masked
    }
    co {
      encrypted
      masked
    }
  }
}

mutation activateExternalId($input: ActivateExternalCustomerByIdInput!) {
  activateExternalCustomerById(input: $input) {
    success
    token {
      value
    }
  }
}

mutation activateExternalToken($input: String!) {
  activateExternalCustomerByToken(input: { externalCustomerToken: $input }) {
    success
    customer {
      externalId
      firstName {
        encrypted
        masked
      }
      email {
        encrypted
        masked
      }
      lastName {
        encrypted
        masked
      }
      address {
        encrypted
        masked
      }
      postalCode {
        encrypted
        masked
      }
      mobilePhoneNumber {
        encrypted
        masked
      }
      city {
        encrypted
        masked
      }
      co {
        encrypted
        masked
      }
    }
  }
}

mutation loginExternalCustomer($input: LoginExternalCustomerInput!) {
  loginExternalCustomer(input: $input) {
    token {
      value
    }
  }
}
