query LookupQuery($key: String!) {
  personLookup(key: $key) {
    firstName {
      encrypted
      masked
    }
    lastName {
      encrypted
      masked
    }
    streetname {
      encrypted
      masked
    }
    postalCode {
      encrypted
      masked
    }
    mobilePhoneNumber {
      encrypted
      masked
    }
    city {
      encrypted
      masked
    }
    co {
      encrypted
      masked
    }
  }
}
